# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PythonFuncs.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PythonFuncs.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x11PythonFuncs.proto\"\x06\n\x04Void\"\"\n\ndiv_params\x12\t\n\x01x\x18\x01 \x01(\x05\x12\t\n\x01y\x18\x02 \x01(\x05\"\x17\n\ndiv_return\x12\t\n\x01z\x18\x01 \x01(\x02\"/\n\x15\x63oncat_strings_params\x12\x16\n\x0e\x61rr_of_strings\x18\x01 \x03(\t\"\'\n\x15\x63oncat_strings_return\x12\x0e\n\x06result\x18\x01 \x01(\t\"3\n\x16\x63\x61lculate_score_params\x12\x19\n\x05gdata\x18\x01 \x01(\x0b\x32\n.game_data\"5\n\x16\x63\x61lculate_score_return\x12\x1b\n\x06gscore\x18\x01 \x01(\x0b\x32\x0b.game_score\"A\n\tgame_data\x12\x0e\n\x06player\x18\x01 \x01(\t\x12\x11\n\tpawn_wins\x18\x02 \x01(\x05\x12\x11\n\tboss_wins\x18\x03 \x01(\x05\"+\n\ngame_score\x12\x0e\n\x06player\x18\x01 \x01(\t\x12\r\n\x05score\x18\x02 \x01(\x05\"E\n\x11gen_scores_return\x12\x1b\n\x06scores\x18\x01 \x03(\x0b\x32\x0b.game_score\x12\x13\n\x0btotal_score\x18\x02 \x01(\x05\x32\x8f\x01\n\rPythonicUtils\x12\x1b\n\x0bhello_world\x12\x05.Void\x1a\x05.Void\x12\x1f\n\x03\x64iv\x12\x0b.div_params\x1a\x0b.div_return\x12@\n\x0e\x63oncat_strings\x12\x16.concat_strings_params\x1a\x16.concat_strings_return2|\n\x0c\x43omplexTypes\x12\x43\n\x0f\x63\x61lculate_score\x12\x17.calculate_score_params\x1a\x17.calculate_score_return\x12\'\n\ngen_scores\x12\x05.Void\x1a\x12.gen_scores_returnb\x06proto3'
)




_VOID = _descriptor.Descriptor(
  name='Void',
  full_name='Void',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=21,
  serialized_end=27,
)


_DIV_PARAMS = _descriptor.Descriptor(
  name='div_params',
  full_name='div_params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='div_params.x', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='y', full_name='div_params.y', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=29,
  serialized_end=63,
)


_DIV_RETURN = _descriptor.Descriptor(
  name='div_return',
  full_name='div_return',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='z', full_name='div_return.z', index=0,
      number=1, type=2, cpp_type=6, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=65,
  serialized_end=88,
)


_CONCAT_STRINGS_PARAMS = _descriptor.Descriptor(
  name='concat_strings_params',
  full_name='concat_strings_params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='arr_of_strings', full_name='concat_strings_params.arr_of_strings', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=137,
)


_CONCAT_STRINGS_RETURN = _descriptor.Descriptor(
  name='concat_strings_return',
  full_name='concat_strings_return',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='concat_strings_return.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=139,
  serialized_end=178,
)


_CALCULATE_SCORE_PARAMS = _descriptor.Descriptor(
  name='calculate_score_params',
  full_name='calculate_score_params',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gdata', full_name='calculate_score_params.gdata', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=180,
  serialized_end=231,
)


_CALCULATE_SCORE_RETURN = _descriptor.Descriptor(
  name='calculate_score_return',
  full_name='calculate_score_return',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='gscore', full_name='calculate_score_return.gscore', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=233,
  serialized_end=286,
)


_GAME_DATA = _descriptor.Descriptor(
  name='game_data',
  full_name='game_data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player', full_name='game_data.player', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='pawn_wins', full_name='game_data.pawn_wins', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='boss_wins', full_name='game_data.boss_wins', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=353,
)


_GAME_SCORE = _descriptor.Descriptor(
  name='game_score',
  full_name='game_score',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='player', full_name='game_score.player', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='score', full_name='game_score.score', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=355,
  serialized_end=398,
)


_GEN_SCORES_RETURN = _descriptor.Descriptor(
  name='gen_scores_return',
  full_name='gen_scores_return',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='scores', full_name='gen_scores_return.scores', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='total_score', full_name='gen_scores_return.total_score', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=400,
  serialized_end=469,
)

_CALCULATE_SCORE_PARAMS.fields_by_name['gdata'].message_type = _GAME_DATA
_CALCULATE_SCORE_RETURN.fields_by_name['gscore'].message_type = _GAME_SCORE
_GEN_SCORES_RETURN.fields_by_name['scores'].message_type = _GAME_SCORE
DESCRIPTOR.message_types_by_name['Void'] = _VOID
DESCRIPTOR.message_types_by_name['div_params'] = _DIV_PARAMS
DESCRIPTOR.message_types_by_name['div_return'] = _DIV_RETURN
DESCRIPTOR.message_types_by_name['concat_strings_params'] = _CONCAT_STRINGS_PARAMS
DESCRIPTOR.message_types_by_name['concat_strings_return'] = _CONCAT_STRINGS_RETURN
DESCRIPTOR.message_types_by_name['calculate_score_params'] = _CALCULATE_SCORE_PARAMS
DESCRIPTOR.message_types_by_name['calculate_score_return'] = _CALCULATE_SCORE_RETURN
DESCRIPTOR.message_types_by_name['game_data'] = _GAME_DATA
DESCRIPTOR.message_types_by_name['game_score'] = _GAME_SCORE
DESCRIPTOR.message_types_by_name['gen_scores_return'] = _GEN_SCORES_RETURN
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Void = _reflection.GeneratedProtocolMessageType('Void', (_message.Message,), {
  'DESCRIPTOR' : _VOID,
  '__module__' : 'PythonFuncs_pb2'
  # @@protoc_insertion_point(class_scope:Void)
  })
_sym_db.RegisterMessage(Void)

div_params = _reflection.GeneratedProtocolMessageType('div_params', (_message.Message,), {
  'DESCRIPTOR' : _DIV_PARAMS,
  '__module__' : 'PythonFuncs_pb2'
  # @@protoc_insertion_point(class_scope:div_params)
  })
_sym_db.RegisterMessage(div_params)

div_return = _reflection.GeneratedProtocolMessageType('div_return', (_message.Message,), {
  'DESCRIPTOR' : _DIV_RETURN,
  '__module__' : 'PythonFuncs_pb2'
  # @@protoc_insertion_point(class_scope:div_return)
  })
_sym_db.RegisterMessage(div_return)

concat_strings_params = _reflection.GeneratedProtocolMessageType('concat_strings_params', (_message.Message,), {
  'DESCRIPTOR' : _CONCAT_STRINGS_PARAMS,
  '__module__' : 'PythonFuncs_pb2'
  # @@protoc_insertion_point(class_scope:concat_strings_params)
  })
_sym_db.RegisterMessage(concat_strings_params)

concat_strings_return = _reflection.GeneratedProtocolMessageType('concat_strings_return', (_message.Message,), {
  'DESCRIPTOR' : _CONCAT_STRINGS_RETURN,
  '__module__' : 'PythonFuncs_pb2'
  # @@protoc_insertion_point(class_scope:concat_strings_return)
  })
_sym_db.RegisterMessage(concat_strings_return)

calculate_score_params = _reflection.GeneratedProtocolMessageType('calculate_score_params', (_message.Message,), {
  'DESCRIPTOR' : _CALCULATE_SCORE_PARAMS,
  '__module__' : 'PythonFuncs_pb2'
  # @@protoc_insertion_point(class_scope:calculate_score_params)
  })
_sym_db.RegisterMessage(calculate_score_params)

calculate_score_return = _reflection.GeneratedProtocolMessageType('calculate_score_return', (_message.Message,), {
  'DESCRIPTOR' : _CALCULATE_SCORE_RETURN,
  '__module__' : 'PythonFuncs_pb2'
  # @@protoc_insertion_point(class_scope:calculate_score_return)
  })
_sym_db.RegisterMessage(calculate_score_return)

game_data = _reflection.GeneratedProtocolMessageType('game_data', (_message.Message,), {
  'DESCRIPTOR' : _GAME_DATA,
  '__module__' : 'PythonFuncs_pb2'
  # @@protoc_insertion_point(class_scope:game_data)
  })
_sym_db.RegisterMessage(game_data)

game_score = _reflection.GeneratedProtocolMessageType('game_score', (_message.Message,), {
  'DESCRIPTOR' : _GAME_SCORE,
  '__module__' : 'PythonFuncs_pb2'
  # @@protoc_insertion_point(class_scope:game_score)
  })
_sym_db.RegisterMessage(game_score)

gen_scores_return = _reflection.GeneratedProtocolMessageType('gen_scores_return', (_message.Message,), {
  'DESCRIPTOR' : _GEN_SCORES_RETURN,
  '__module__' : 'PythonFuncs_pb2'
  # @@protoc_insertion_point(class_scope:gen_scores_return)
  })
_sym_db.RegisterMessage(gen_scores_return)



_PYTHONICUTILS = _descriptor.ServiceDescriptor(
  name='PythonicUtils',
  full_name='PythonicUtils',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=472,
  serialized_end=615,
  methods=[
  _descriptor.MethodDescriptor(
    name='hello_world',
    full_name='PythonicUtils.hello_world',
    index=0,
    containing_service=None,
    input_type=_VOID,
    output_type=_VOID,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='div',
    full_name='PythonicUtils.div',
    index=1,
    containing_service=None,
    input_type=_DIV_PARAMS,
    output_type=_DIV_RETURN,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='concat_strings',
    full_name='PythonicUtils.concat_strings',
    index=2,
    containing_service=None,
    input_type=_CONCAT_STRINGS_PARAMS,
    output_type=_CONCAT_STRINGS_RETURN,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PYTHONICUTILS)

DESCRIPTOR.services_by_name['PythonicUtils'] = _PYTHONICUTILS


_COMPLEXTYPES = _descriptor.ServiceDescriptor(
  name='ComplexTypes',
  full_name='ComplexTypes',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=617,
  serialized_end=741,
  methods=[
  _descriptor.MethodDescriptor(
    name='calculate_score',
    full_name='ComplexTypes.calculate_score',
    index=0,
    containing_service=None,
    input_type=_CALCULATE_SCORE_PARAMS,
    output_type=_CALCULATE_SCORE_RETURN,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='gen_scores',
    full_name='ComplexTypes.gen_scores',
    index=1,
    containing_service=None,
    input_type=_VOID,
    output_type=_GEN_SCORES_RETURN,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_COMPLEXTYPES)

DESCRIPTOR.services_by_name['ComplexTypes'] = _COMPLEXTYPES

# @@protoc_insertion_point(module_scope)
