// Code generated by protoc-gen-go. DO NOT EDIT.
// source: App.proto

package bar

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//--------------------------------------------------------------------
// param1 comment
type Params1 struct {
	P1                   []string `protobuf:"bytes,1,rep,name=p1,proto3" json:"p1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Params1) Reset()         { *m = Params1{} }
func (m *Params1) String() string { return proto.CompactTextString(m) }
func (*Params1) ProtoMessage()    {}
func (*Params1) Descriptor() ([]byte, []int) {
	return fileDescriptor_3adb4add8019e98f, []int{0}
}

func (m *Params1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Params1.Unmarshal(m, b)
}
func (m *Params1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Params1.Marshal(b, m, deterministic)
}
func (m *Params1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params1.Merge(m, src)
}
func (m *Params1) XXX_Size() int {
	return xxx_messageInfo_Params1.Size(m)
}
func (m *Params1) XXX_DiscardUnknown() {
	xxx_messageInfo_Params1.DiscardUnknown(m)
}

var xxx_messageInfo_Params1 proto.InternalMessageInfo

func (m *Params1) GetP1() []string {
	if m != nil {
		return m.P1
	}
	return nil
}

//--------------------------------------------------------------------
type Return1 struct {
	R1                   string   `protobuf:"bytes,1,opt,name=r1,proto3" json:"r1,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Return1) Reset()         { *m = Return1{} }
func (m *Return1) String() string { return proto.CompactTextString(m) }
func (*Return1) ProtoMessage()    {}
func (*Return1) Descriptor() ([]byte, []int) {
	return fileDescriptor_3adb4add8019e98f, []int{1}
}

func (m *Return1) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Return1.Unmarshal(m, b)
}
func (m *Return1) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Return1.Marshal(b, m, deterministic)
}
func (m *Return1) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Return1.Merge(m, src)
}
func (m *Return1) XXX_Size() int {
	return xxx_messageInfo_Return1.Size(m)
}
func (m *Return1) XXX_DiscardUnknown() {
	xxx_messageInfo_Return1.DiscardUnknown(m)
}

var xxx_messageInfo_Return1 proto.InternalMessageInfo

func (m *Return1) GetR1() string {
	if m != nil {
		return m.R1
	}
	return ""
}

//--------------------------------------------------------------------
type Params2 struct {
	P21                  string   `protobuf:"bytes,1,opt,name=p21,proto3" json:"p21,omitempty"`
	P22                  *Params1 `protobuf:"bytes,2,opt,name=p22,proto3" json:"p22,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Params2) Reset()         { *m = Params2{} }
func (m *Params2) String() string { return proto.CompactTextString(m) }
func (*Params2) ProtoMessage()    {}
func (*Params2) Descriptor() ([]byte, []int) {
	return fileDescriptor_3adb4add8019e98f, []int{2}
}

func (m *Params2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Params2.Unmarshal(m, b)
}
func (m *Params2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Params2.Marshal(b, m, deterministic)
}
func (m *Params2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params2.Merge(m, src)
}
func (m *Params2) XXX_Size() int {
	return xxx_messageInfo_Params2.Size(m)
}
func (m *Params2) XXX_DiscardUnknown() {
	xxx_messageInfo_Params2.DiscardUnknown(m)
}

var xxx_messageInfo_Params2 proto.InternalMessageInfo

func (m *Params2) GetP21() string {
	if m != nil {
		return m.P21
	}
	return ""
}

func (m *Params2) GetP22() *Params1 {
	if m != nil {
		return m.P22
	}
	return nil
}

//--------------------------------------------------------------------
type Return2 struct {
	R21                  string   `protobuf:"bytes,1,opt,name=r21,proto3" json:"r21,omitempty"`
	R22                  *Return1 `protobuf:"bytes,2,opt,name=r22,proto3" json:"r22,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Return2) Reset()         { *m = Return2{} }
func (m *Return2) String() string { return proto.CompactTextString(m) }
func (*Return2) ProtoMessage()    {}
func (*Return2) Descriptor() ([]byte, []int) {
	return fileDescriptor_3adb4add8019e98f, []int{3}
}

func (m *Return2) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Return2.Unmarshal(m, b)
}
func (m *Return2) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Return2.Marshal(b, m, deterministic)
}
func (m *Return2) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Return2.Merge(m, src)
}
func (m *Return2) XXX_Size() int {
	return xxx_messageInfo_Return2.Size(m)
}
func (m *Return2) XXX_DiscardUnknown() {
	xxx_messageInfo_Return2.DiscardUnknown(m)
}

var xxx_messageInfo_Return2 proto.InternalMessageInfo

func (m *Return2) GetR21() string {
	if m != nil {
		return m.R21
	}
	return ""
}

func (m *Return2) GetR22() *Return1 {
	if m != nil {
		return m.R22
	}
	return nil
}

func init() {
	proto.RegisterType((*Params1)(nil), "Params1")
	proto.RegisterType((*Return1)(nil), "Return1")
	proto.RegisterType((*Params2)(nil), "Params2")
	proto.RegisterType((*Return2)(nil), "Return2")
}

func init() { proto.RegisterFile("App.proto", fileDescriptor_3adb4add8019e98f) }

var fileDescriptor_3adb4add8019e98f = []byte{
	// 193 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0xd0, 0xc1, 0xcb, 0x82, 0x30,
	0x18, 0xc7, 0x71, 0x9c, 0xf0, 0xbe, 0xba, 0x17, 0x5e, 0x62, 0x11, 0x98, 0x27, 0xf1, 0xe4, 0x49,
	0xd9, 0xd3, 0xa1, 0x5b, 0x50, 0x87, 0xce, 0x61, 0xb7, 0x6e, 0x53, 0x16, 0x04, 0xd9, 0xc6, 0x93,
	0x45, 0x7f, 0x7e, 0x3c, 0x53, 0x57, 0x37, 0xf1, 0xb3, 0xef, 0x6f, 0x30, 0x1e, 0x6f, 0xad, 0x2d,
	0x2d, 0x9a, 0xde, 0xe4, 0x4b, 0xfe, 0x7b, 0x50, 0xa8, 0xba, 0xbb, 0x14, 0xff, 0x9c, 0x59, 0x99,
	0x04, 0x59, 0x58, 0xc4, 0x35, 0xb3, 0x92, 0xa8, 0xd6, 0xfd, 0x03, 0x6f, 0x8e, 0x90, 0x28, 0x20,
	0x42, 0x99, 0xaf, 0xa7, 0x0a, 0xc4, 0x8c, 0x87, 0x16, 0x26, 0xa3, 0x4f, 0x91, 0xd2, 0x1f, 0x48,
	0x58, 0x16, 0x14, 0x7f, 0x10, 0x95, 0xe3, 0x3c, 0x19, 0x50, 0x38, 0x6c, 0xba, 0x10, 0x3f, 0x21,
	0x0e, 0x21, 0x7e, 0x85, 0xe3, 0xe5, 0x64, 0x00, 0x1b, 0x1e, 0x1d, 0x35, 0x3e, 0x2f, 0xad, 0x96,
	0x22, 0xe1, 0x6c, 0x2f, 0x85, 0x5f, 0x4e, 0xfd, 0x51, 0x27, 0xe0, 0x05, 0xbc, 0xc0, 0x6e, 0x71,
	0x9a, 0xeb, 0x97, 0xea, 0xec, 0x55, 0x97, 0xad, 0xe9, 0xaa, 0xb3, 0x31, 0x55, 0xa3, 0xb0, 0xf9,
	0x71, 0xaf, 0xb0, 0x7a, 0x07, 0x00, 0x00, 0xff, 0xff, 0xb6, 0x89, 0x63, 0xd5, 0x12, 0x01, 0x00,
	0x00,
}
